### ISSUE TITLE
Reporting a typo in comments - File: vocabulary.csv

### ISSUE THREAD

**Issue by architapatelis** [callmeed/trivia_factory#1]
Hi @callmeed I was looking to make open source contributions when I came across this project. Upon reviewing the code I notice a small typo you have, Line 6 in [academy_awards_question.rb](https://github.com/callmeed/trivia_factory/blob/master/lib/trivia_factory/academy_awards_question.rb) and Line 8 in [sports_question.rb](https://github.com/callmeed/trivia_factory/blob/master/lib/trivia_factory/sports_question.rb) . I think you need to replace `File: vocabulary.csv` with `File: academy_awards.csv` and `File: sports_champions.csv` respectively. 

The other thing that seemed odd to me in both those files is, the `question` variable, you have an instance of `class Question` and `class VocabularyQuestion`. I don't understand why that is, I would think it should be more like the code for [capital_cities_question.rb](https://github.com/callmeed/trivia_factory/blob/master/lib/trivia_factory/capital_cities_question.rb), with just an instance of `class Question`. 

```ruby
question = TriviaFactory::Question.new
data = fetch_csv('academy_awards')
answer_row = data.sample
question = TriviaFactory::VocabularyQuestion.new
```

I know this is still work in progress, but I figured I would raise the issue in case it helps you out.

**Comment by callmeed** [comment]
Nice catch. Fixed.

@architapatelis If you're interested in contributing or being a collaborator, please let me know.
