### ISSUE TITLE
Contribution

### ISSUE THREAD

**Issue by architapatelis** [callmeed/trivia_factory#3]
@callmeed I would like to contribute to your project. I was thinking something on the lines of the academy awards trivia, I could do trivia for Grammy Award for Album of the Year. [Wikipedia](https://en.wikipedia.org/wiki/Grammy_Award_for_Album_of_the_Year) has a list with the _year_, _winners_ and _work/album_. So I can use that for the data. Let me know if that's alright with you. thanks!

**Comment by callmeed** [comment]
Yeah that'd be great. Generally what I do is copy from an HTML table and paste into a Google Docs spreadsheet. Then, I clean it up and download it as a CSV file. 

Shoot me an email if you'd like me to share my Google Doc with you.
